### ISSUE TITLE
Bug: Getting duplicate emails

### ISSUE THREAD

**Issue by jeremybull** [mikehadlow/Suteki.TardisBank#19]
When my kid makes a request to withdraw cash, I usually get two emails. For example tonight 4/1 at 7:01pm I got two emails stating "Lucas would like to withdraw $5.00". He only made the request once.

**Comment by jeremybull** [comment]
Mike, just doing some cleanup here. Either you fixed this, or it fixed itself. I saw it happen one more time on 4/14/11 and then never again since then.

**Comment by mikehadlow** [comment]
Thanks Jeremy! I see that you're still using TardisBank all these years later :)
